apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: demo-konflux-test-gitops
  description: This is GitOps manifest for demo-konflux-test   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=demo-konflux-test
    backstage.io/kubernetes-id: demo-konflux-test 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: demo-konflux-test
spec:
  type: gitops
  owner: user:default/deanpeterson 
  lifecycle: experimental
  dependsOn:
    - component:demo-konflux-test
